#!/usr/bin/env python3
"""
Test Suite Orchestrator (vault-quality framework v2)

Per-vault, per-language test framework. Drives the production /query path
through fresh-context subagents, fans out evaluation to N independent
evaluators, computes inter-rater statistics, and produces a narrative report.

Layout produced under vaults/{name}/tests/:

    questions.{lang}.yaml                              # generated by Phase 1
    raw-responses/{label}/run-N/{lang}/
        prompts/Q*.md                                  # answering-agent prompts
        prompts/evaluator-E{i}.md                      # N evaluator prompts
        prompts/aggregator.md                          # 1 aggregator prompt
        Q*.json                                        # answering-agent outputs
        evaluation-E{i}.json                           # N evaluator outputs
        tokens.json                                    # cost telemetry
        stats.json                                     # per-Q mean+std across evals
    results/{label}.{lang}.json                        # consolidated, IRR-aware
    reports/{label}.{lang}.md                          # aggregator narrative
    history.md                                         # chronological log

Subcommands:

    --generate-questions  --label LABEL --lang LANG [--count N] [--mix A:B:C] [--regenerate] [--questions-from VAULT|PATH]
    --prepare             --label LABEL --lang LANG [--run N] [--read-queries]
    --prepare-evaluator   --label LABEL --lang LANG [--run N] [--evaluators N] [--read-queries]
    --prepare-aggregator  --label LABEL --lang LANG [--run N]
    --consolidate         --label LABEL --lang LANG [--run N]
    --update-tokens       --label LABEL --lang LANG [--run N]
    --compare             --from FROM --to TO --lang LANG
    --check-repetition    --from FROM --to TO --lang LANG

ALL test artifacts live INSIDE THIS REPO under vaults/{name}/tests/. The vault
is read-only context for agents; agents NEVER write to vault data.
"""

import argparse
import json
import math
import os
import sys
import yaml
from datetime import date, datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / ".claude" / "scripts"))
from config import VaultConfig, read_config  # noqa: E402

# Lazy-initialized directory structure (resolved after VaultConfig())
_cfg: VaultConfig = None
TESTS_DIR: Path = None
RAW_DIR: Path = None
RESULTS_DIR: Path = None
REPORTS_DIR: Path = None
COMPARISONS_DIR: Path = None
HISTORY_FILE: Path = None
VAULT_PATH: str = None
VAULT_NAME: str = None
TESTS_CFG: dict = {}

TEMPLATES_DIR = REPO_ROOT / ".claude" / "templates" / "tests"
AGENT_TEMPLATE_FILE = TEMPLATES_DIR / "agent.md.template"
EVALUATOR_TEMPLATE_FILE = TEMPLATES_DIR / "evaluator.md.template"
REFINER_TEMPLATE_FILE = TEMPLATES_DIR / "refiner.md.template"
QUESTION_GENERATOR_TEMPLATE_FILE = TEMPLATES_DIR / "question-generator.md.template"
AGGREGATOR_TEMPLATE_FILE = TEMPLATES_DIR / "aggregator.md.template"


def _init_vault_config(vault_arg: str = None):
    """Initialize VaultConfig and set up directory paths. Call once from main()."""
    global _cfg, TESTS_DIR, RAW_DIR, RESULTS_DIR, REPORTS_DIR, COMPARISONS_DIR
    global HISTORY_FILE, VAULT_PATH, VAULT_NAME, TESTS_CFG

    _cfg = VaultConfig(vault_arg or None)

    VAULT_NAME = _cfg.name
    TESTS_DIR = REPO_ROOT / "vaults" / VAULT_NAME / "tests"
    RAW_DIR = TESTS_DIR / "raw-responses"
    RESULTS_DIR = TESTS_DIR / "results"
    REPORTS_DIR = TESTS_DIR / "reports"
    COMPARISONS_DIR = TESTS_DIR / "comparisons"
    HISTORY_FILE = TESTS_DIR / "history.md"
    VAULT_PATH = os.environ.get("VAULT_PATH", str(_cfg.vault_path))

    TESTS_CFG = _cfg.get("tests") or {}

    _apply_evaluation_overrides()


def _apply_evaluation_overrides() -> None:
    """Read RUBRIC weights from vault.yml.tests.rubric (per-vault default).

    Falls back to .claude/wikiforge/config.yaml.evaluation.rubric, then to
    the hardcoded defaults below.
    """
    global ALPHA
    weights = TESTS_CFG.get("rubric") or {}
    if not weights:
        cfg = read_config(REPO_ROOT)
        weights = (cfg.get("evaluation") or {}).get("rubric") or {}
    for dim, w in weights.items():
        if dim in RUBRIC:
            try:
                RUBRIC[dim]["weight"] = float(w)
            except (TypeError, ValueError):
                pass
    cfg = read_config(REPO_ROOT)
    alpha_override = (cfg.get("evaluation") or {}).get("composite_alpha")
    if alpha_override is not None:
        try:
            ALPHA = float(alpha_override)
        except (TypeError, ValueError):
            pass

OUTPUT_TOKEN_WEIGHT = 6
CHARS_PER_TOKEN = 4.0

RUBRIC_VERSION = "2.0"
RUBRIC = {
    "completeness":      {"weight": 0.25, "label": "Completeness"},
    "accuracy":          {"weight": 0.25, "label": "Accuracy"},
    "language_purity":   {"weight": 0.15, "label": "Language purity"},
    "tone":              {"weight": 0.15, "label": "Tone"},
    "format_compliance": {"weight": 0.20, "label": "Format compliance"},
}

# === Decision parameters (kept for --compare/--check-repetition) ===
DECISION_VERSION = "2.0"
ALPHA = 0.85
FLOOR_WEIGHTED_AVG_ABS = 7.0
FLOOR_ACCURACY_ABS = 8.0
FLOOR_ANY_DIM_DROP_ABS = 1.0
COMPOSITE_IMPLEMENT = 0.005
COMPOSITE_REVERT = -0.005
REP_COMPOSITE_NOISE = 0.015
REP_MAX_RUNS = 3

DEFAULT_COUNT = 15
DEFAULT_MIX = {"A": 5, "B": 7, "C": 3}
DEFAULT_EVALUATORS = 5
DEFAULT_DISAGREEMENT_THRESHOLD = 1.5


def _tests_default(key, fallback):
    val = TESTS_CFG.get(key)
    return val if val is not None else fallback


# ----------------------------------------------------------------------
# Safety
# ----------------------------------------------------------------------

def _ensure_under_tests(path: Path):
    abs_path = path.resolve()
    tests_resolved = TESTS_DIR.resolve()
    if tests_resolved not in abs_path.parents and abs_path != tests_resolved:
        raise RuntimeError(f"SAFETY: refusing to write outside {TESTS_DIR}: {abs_path}")


# ----------------------------------------------------------------------
# Run dirs
# ----------------------------------------------------------------------

def _run_dir(label, run, lang):
    return RAW_DIR / label / f"run-{run}" / lang


def _run_root(label, run):
    return RAW_DIR / label / f"run-{run}"


def _iter_run_numbers(label):
    base = RAW_DIR / label
    if not base.exists():
        return
    for p in base.iterdir():
        if not (p.is_dir() and p.name.startswith("run-")):
            continue
        try:
            yield int(p.name.split("-")[1]), p
        except (IndexError, ValueError):
            continue


def _next_run(label, lang=None):
    """Return the next run number to write into.

    If `lang` is given, a run is "occupied" only when it has Q*.json for that
    lang. This lets Phase 2 reuse the same run-N that Phase 1 created prompts
    in (Phase 1 alone leaves an empty Q*.json-less run dir), and lets two
    langs of the same label share the same run number.
    """
    occupied = []
    for n, p in _iter_run_numbers(label):
        if lang is None or list((p / lang).glob("Q*.json")):
            occupied.append(n)
    return (max(occupied) + 1) if occupied else 1


def _existing_runs(label, lang=None):
    runs = []
    for n, p in _iter_run_numbers(label):
        if lang is None or list((p / lang).glob("Q*.json")):
            runs.append(n)
    return sorted(runs)


def _resolve_run(label, run, lang=None):
    if run is not None:
        return run
    runs = _existing_runs(label, lang)
    if not runs:
        suffix = f" lang={lang}" if lang else ""
        print(f"[ERR] No runs found for {label}{suffix}")
        sys.exit(1)
    return runs[-1]


# ----------------------------------------------------------------------
# Questions
# ----------------------------------------------------------------------

def _questions_file(lang):
    return TESTS_DIR / f"questions.{lang}.yaml"


def load_questions(lang):
    qf = _questions_file(lang)
    if not qf.exists():
        print(f"[ERR] questions file missing: {qf}")
        print("      Run --generate-questions first.")
        sys.exit(1)
    return yaml.safe_load(qf.read_text())


def _parse_mix(mix_str):
    """Parse '5:7:3' → {A:5, B:7, C:3}. Or pass dict-like already."""
    if isinstance(mix_str, dict):
        return {k.upper(): int(v) for k, v in mix_str.items()}
    parts = mix_str.split(":")
    if len(parts) != 3:
        raise ValueError(f"--mix must be A:B:C (got {mix_str!r})")
    return {"A": int(parts[0]), "B": int(parts[1]), "C": int(parts[2])}


def _resolve_questions_source(src: str, lang: str) -> Path:
    """Resolve --questions-from value to a path.

    If `src` looks like a path (has a separator or ends with .yaml), use as-is.
    Otherwise treat as a vault name → vaults/{src}/tests/questions.{lang}.yaml.
    """
    if "/" in src or src.endswith(".yaml") or src.endswith(".yml"):
        p = Path(src)
        return p if p.is_absolute() else (REPO_ROOT / p)
    return REPO_ROOT / "vaults" / src / "tests" / f"questions.{lang}.yaml"


def generate_questions_prompt(label, lang, count, mix, regenerate, questions_from=None):
    """Write a question-generator subagent prompt and stop.

    The Claude orchestrator launches the subagent, which writes the YAML.

    If `questions_from` is set, copy the source YAML into the target vault
    (overwrite-on-purpose) and skip the subagent prompt entirely.
    """
    qf = _questions_file(lang)

    if questions_from:
        if regenerate:
            print("[ERR] --questions-from and --regenerate are mutually exclusive")
            sys.exit(1)
        src = _resolve_questions_source(questions_from, lang)
        if not src.exists():
            print(f"[ERR] Source questions not found: {src}")
            sys.exit(1)
        if src.resolve() == qf.resolve():
            print(f"[OK] Source and target are the same file ({qf}); no-op")
            return
        qf.parent.mkdir(parents=True, exist_ok=True)
        qf.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"[OK] Copied questions: {src} → {qf}")
        print("     Phase 1 satisfied; orchestrator can skip the generator subagent.")
        return

    if qf.exists() and not regenerate:
        print(f"[OK] {qf} already exists; skipping (pass --regenerate to overwrite)")
        return

    prompt_dir = TESTS_DIR / "raw-responses" / label / "run-1" / lang / "prompts"
    _ensure_under_tests(prompt_dir)
    prompt_dir.mkdir(parents=True, exist_ok=True)
    prompt_path = prompt_dir / "question-generator.md"

    template = QUESTION_GENERATOR_TEMPLATE_FILE.read_text()
    prompt = template.format(
        vault_name=VAULT_NAME,
        vault_path=VAULT_PATH,
        repo_path=str(REPO_ROOT),
        lang=lang,
        count=count,
        n_a=mix["A"],
        n_b=mix["B"],
        n_c=mix["C"],
        today=date.today().isoformat(),
        output_path=str(qf),
    )
    prompt_path.write_text(prompt)
    print(f"[OK] Wrote question-generator prompt: {prompt_path}")
    print(f"     Subagent will write YAML to: {qf}")


# ----------------------------------------------------------------------
# Phase 2 — Answering prompts
# ----------------------------------------------------------------------

def prepare_prompts(label, lang, run=None, read_queries=False):
    if run is None:
        run = _next_run(label, lang)

    questions_data = load_questions(lang)
    questions = questions_data.get("questions", {})
    if not questions:
        print(f"[ERR] questions.{lang}.yaml has no entries")
        sys.exit(1)

    template = AGENT_TEMPLATE_FILE.read_text()
    run_dir = _run_dir(label, run, lang)
    prompts_subdir = run_dir / "prompts"
    _ensure_under_tests(prompts_subdir)
    prompts_subdir.mkdir(parents=True, exist_ok=True)

    queries_clause = (
        "Reading is permitted because --read-queries was set (ablation only)."
        if read_queries else
        "Reading the queries cache is FORBIDDEN — that is the cache of prior /query answers and would defeat the test."
    )

    for qid, qdata in questions.items():
        output_path = run_dir / f"{qid}.json"
        prompt = template.format(
            qid=qid,
            question=qdata["question"],
            level=qdata.get("level", 1),
            output_path=str(output_path),
            vault_path=VAULT_PATH,
            vault_name=VAULT_NAME,
            repo_path=str(REPO_ROOT),
            lang=lang,
            queries_clause=queries_clause,
        )
        (prompts_subdir / f"{qid}.md").write_text(prompt)

    print(f"[OK] Prepared {len(questions)} prompts for {label} run-{run} lang={lang}")
    print(f"     Prompts dir: {prompts_subdir}")
    print(f"     Outputs: {run_dir}/Q*.json")


# ----------------------------------------------------------------------
# Phase 3 — Evaluator fan-out
# ----------------------------------------------------------------------

def _inject_script_word_counts(run_dir, qids):
    """Compute authoritative word count of `response` for each Q*.json and
    write it back as `script_word_count`. Evaluators use this over the agent's
    self-reported `self_assessment.word_count` (which is often missing/wrong).
    """
    updated = 0
    for qid in qids:
        qf = run_dir / f"{qid}.json"
        if not qf.exists():
            continue
        try:
            data = json.loads(qf.read_text())
        except (json.JSONDecodeError, ValueError):
            continue
        response = data.get("response") or ""
        wc = len(response.split())
        if data.get("script_word_count") == wc:
            continue
        data["script_word_count"] = wc
        qf.write_text(json.dumps(data, indent=2, ensure_ascii=False))
        updated += 1
    return updated


def prepare_evaluator(label, lang, run=None, evaluators=None, read_queries=False):
    run = _resolve_run(label, run, lang)
    if evaluators is None:
        evaluators = int(_tests_default("evaluators", DEFAULT_EVALUATORS))

    run_dir = _run_dir(label, run, lang)
    if not run_dir.exists():
        print(f"[ERR] Run dir does not exist: {run_dir}")
        sys.exit(1)

    template = EVALUATOR_TEMPLATE_FILE.read_text()
    questions_data = load_questions(lang)
    n_questions = len(questions_data.get("questions", {}))
    qids = list(questions_data.get("questions", {}).keys())

    n_injected = _inject_script_word_counts(run_dir, qids)
    if n_injected:
        print(f"[OK] Injected script_word_count into {n_injected} Q*.json file(s)")

    response_paths = "\n".join(
        f"   - {run_dir}/Q{i}.json" for i in range(1, n_questions + 1)
    )
    queries_clause = (
        "`{vault_path}/queries/` — permitted because --read-queries was set (ablation only).".replace(
            "{vault_path}", VAULT_PATH
        )
        if read_queries else
        f"`{VAULT_PATH}/queries/` — the cache of prior /query answers; reading would taint the evaluation."
    )

    prompts_dir = run_dir / "prompts"
    prompts_dir.mkdir(parents=True, exist_ok=True)

    for i in range(1, evaluators + 1):
        evaluator_id = f"E{i}"
        output_path = run_dir / f"evaluation-{evaluator_id}.json"
        prompt = template.format(
            label=label,
            run=run,
            lang=lang,
            evaluator_id=evaluator_id,
            evaluator_count=evaluators,
            response_paths=response_paths,
            output_path=str(output_path),
            repo_path=str(REPO_ROOT),
            vault_path=VAULT_PATH,
            rubric_version=RUBRIC_VERSION,
            queries_clause=queries_clause,
            n_questions=n_questions,
        )
        (prompts_dir / f"evaluator-{evaluator_id}.md").write_text(prompt)

    print(f"[OK] Prepared {evaluators} evaluator prompts for {label} run-{run} lang={lang}")
    print(f"     Prompts: {prompts_dir}/evaluator-E*.md")
    print(f"     Outputs: {run_dir}/evaluation-E*.json")


# ----------------------------------------------------------------------
# Phase 5 — Aggregator
# ----------------------------------------------------------------------

def prepare_aggregator(label, lang, run=None):
    run = _resolve_run(label, run, lang)
    run_dir = _run_dir(label, run, lang)
    if not run_dir.exists():
        print(f"[ERR] Run dir does not exist: {run_dir}")
        sys.exit(1)

    stats_path = run_dir / "stats.json"
    if not stats_path.exists():
        print(f"[ERR] stats.json missing — run --consolidate first")
        sys.exit(1)

    eval_files = sorted(run_dir.glob("evaluation-E*.json"))
    if not eval_files:
        print("[ERR] no evaluation-E*.json files found")
        sys.exit(1)

    questions_data = load_questions(lang)
    questions = questions_data.get("questions", {})
    n_questions = len(questions)
    mix = questions_data.get("mix") or {"A": 0, "B": 0, "C": 0}

    response_paths = "\n".join(f"  - {run_dir}/Q{i}.json" for i in range(1, n_questions + 1))
    evaluation_paths = "\n".join(f"  - {p}" for p in eval_files)

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = REPORTS_DIR / f"{label}.{lang}.md"

    template = AGGREGATOR_TEMPLATE_FILE.read_text()
    disagreement = float(_tests_default(
        "thresholds", {}
    ).get("max_dim_disagreement", DEFAULT_DISAGREEMENT_THRESHOLD)) if isinstance(
        _tests_default("thresholds", {}), dict
    ) else DEFAULT_DISAGREEMENT_THRESHOLD

    prompt = template.format(
        label=label,
        lang=lang,
        run=run,
        vault_name=VAULT_NAME,
        vault_path=VAULT_PATH,
        repo_path=str(REPO_ROOT),
        evaluator_count=len(eval_files),
        n_questions=n_questions,
        n_a=mix.get("A", 0),
        n_b=mix.get("B", 0),
        n_c=mix.get("C", 0),
        stats_path=str(stats_path),
        evaluation_paths=evaluation_paths,
        response_paths=response_paths,
        output_path=str(output_path),
        today=date.today().isoformat(),
        disagreement_threshold=disagreement,
    )

    prompts_dir = run_dir / "prompts"
    prompts_dir.mkdir(parents=True, exist_ok=True)
    (prompts_dir / "aggregator.md").write_text(prompt)

    print(f"[OK] Prepared aggregator prompt for {label} run-{run} lang={lang}")
    print(f"     Prompt: {prompts_dir}/aggregator.md")
    print(f"     Report will be written to: {output_path}")


# ----------------------------------------------------------------------
# Phase 4 — Consolidate (mean + std across N evaluators)
# ----------------------------------------------------------------------

def _estimate_output_tokens(text):
    return int(len(text) / CHARS_PER_TOKEN)


def _build_tokens_summary(run_dir, qids, eval_files, label, lang):
    """Estimate per-stage input/output tokens from on-disk artifacts.

    Method: char-length / CHARS_PER_TOKEN. These are NOT real API counters —
    Claude Code subagents do not expose usage back to the orchestrator. The
    estimates are useful for cross-run comparisons (relative cost trends) but
    absolute values should be read as approximations.

    Schema:
      answers.{qid}, evaluations.{Eid}, aggregator → {input, output, total}
      *_total → per-stage sums
      grand_total → sum across all stages
    """
    def est(s):
        return int(len(s) / CHARS_PER_TOKEN) if s else 0

    answers = {}
    for qid in qids:
        prompt_file = run_dir / "prompts" / f"{qid}.md"
        response_file = run_dir / f"{qid}.json"
        in_tok = est(prompt_file.read_text()) if prompt_file.exists() else 0
        out_tok = 0
        if response_file.exists():
            try:
                resp = json.loads(response_file.read_text())
                out_tok = est(resp.get("response") or "")
            except (json.JSONDecodeError, ValueError):
                pass
        answers[qid] = {
            "input_tokens": in_tok,
            "output_tokens": out_tok,
            "total_tokens": in_tok + out_tok,
        }

    evaluations = {}
    for ef in eval_files:
        eid = ef.stem.replace("evaluation-", "")
        prompt_file = run_dir / "prompts" / f"evaluator-{eid}.md"
        in_tok = est(prompt_file.read_text()) if prompt_file.exists() else 0
        out_tok = est(ef.read_text())
        evaluations[eid] = {
            "input_tokens": in_tok,
            "output_tokens": out_tok,
            "total_tokens": in_tok + out_tok,
        }

    aggregator = None
    agg_prompt = run_dir / "prompts" / "aggregator.md"
    agg_report = REPORTS_DIR / f"{label}.{lang}.md"
    if agg_prompt.exists():
        in_tok = est(agg_prompt.read_text())
        out_tok = est(agg_report.read_text()) if agg_report.exists() else 0
        aggregator = {
            "input_tokens": in_tok,
            "output_tokens": out_tok,
            "total_tokens": in_tok + out_tok,
        }

    def _sum_section(section):
        return {
            "input_tokens": sum(v["input_tokens"] for v in section.values()),
            "output_tokens": sum(v["output_tokens"] for v in section.values()),
            "total_tokens": sum(v["total_tokens"] for v in section.values()),
        }

    answers_total = _sum_section(answers)
    evaluations_total = _sum_section(evaluations)
    agg_total = aggregator if aggregator else {"input_tokens": 0, "output_tokens": 0, "total_tokens": 0}

    return {
        "method": f"char-length / {CHARS_PER_TOKEN} estimate (not real API counters)",
        "answers": answers,
        "answers_total": answers_total,
        "evaluations": evaluations,
        "evaluations_total": evaluations_total,
        "aggregator": aggregator,
        "grand_total": {
            "input_tokens": answers_total["input_tokens"] + evaluations_total["input_tokens"] + agg_total["input_tokens"],
            "output_tokens": answers_total["output_tokens"] + evaluations_total["output_tokens"] + agg_total["output_tokens"],
            "total_tokens": answers_total["total_tokens"] + evaluations_total["total_tokens"] + agg_total["total_tokens"],
        },
    }


def _write_tokens_file(label, lang, run):
    """Build tokens.json from on-disk artifacts and write it."""
    run_dir = _run_dir(label, run, lang)
    if not run_dir.exists():
        print(f"[ERR] Run dir does not exist: {run_dir}")
        sys.exit(1)
    questions_data = load_questions(lang)
    qids = list(questions_data.get("questions", {}).keys())
    eval_files = sorted(run_dir.glob("evaluation-E*.json"))

    summary = _build_tokens_summary(run_dir, qids, eval_files, label, lang)
    tokens_path = run_dir / "tokens.json"
    _ensure_under_tests(tokens_path)
    tokens_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False))
    return tokens_path, summary


def update_tokens(label, lang, run=None):
    run = _resolve_run(label, run, lang)
    tokens_path, summary = _write_tokens_file(label, lang, run)
    gt = summary["grand_total"]
    print(f"[OK] Wrote {tokens_path}")
    print(f"     grand_total: in={gt['input_tokens']:,}  out={gt['output_tokens']:,}  total={gt['total_tokens']:,}")


def _weighted_avg_from_dict(scores):
    return round(sum(scores.get(d, 0) * c["weight"] for d, c in RUBRIC.items()), 3)


def _mean_std(values):
    if not values:
        return 0.0, 0.0
    n = len(values)
    mean = sum(values) / n
    if n < 2:
        return mean, 0.0
    var = sum((v - mean) ** 2 for v in values) / (n - 1)
    return mean, math.sqrt(var)


def consolidate_results(label, lang, run=None):
    run = _resolve_run(label, run)
    run_dir = _run_dir(label, run, lang)
    if not run_dir.exists():
        print(f"[ERR] Run dir does not exist: {run_dir}")
        sys.exit(1)

    eval_files = sorted(run_dir.glob("evaluation-E*.json"))
    if not eval_files:
        print(f"[ERR] No evaluation-E*.json files in {run_dir}")
        sys.exit(1)

    questions_data = load_questions(lang)
    questions = questions_data.get("questions", {})
    qids = list(questions.keys())

    # Load each evaluator's scores per Q per dim
    evaluators = []
    for ef in eval_files:
        data = json.loads(ef.read_text())
        evaluators.append(data)

    disagreement_threshold = float(
        (TESTS_CFG.get("thresholds") or {}).get(
            "max_dim_disagreement", DEFAULT_DISAGREEMENT_THRESHOLD
        )
    )

    per_q = {}
    flagged_qs = []
    for qid in qids:
        per_dim = {}
        for d in RUBRIC:
            scores = []
            for ev in evaluators:
                qeval = (ev.get("evaluations") or {}).get(qid, {})
                v = qeval.get(d)
                if v is not None:
                    scores.append(float(v))
            mean, std = _mean_std(scores)
            per_dim[d] = {
                "mean": round(mean, 3),
                "std": round(std, 3),
                "n_evaluators": len(scores),
                "scores": scores,
                "flagged": std > disagreement_threshold,
            }
            if std > disagreement_threshold:
                flagged_qs.append({"qid": qid, "dim": d, "mean": mean, "std": std})

        wavg = _weighted_avg_from_dict({d: per_dim[d]["mean"] for d in RUBRIC})
        per_q[qid] = {
            "level": questions[qid].get("level"),
            "regime": questions[qid].get("regime"),
            "topic": questions[qid].get("topic"),
            "dims": per_dim,
            "weighted_avg": wavg,
        }

    dim_aggregate = {}
    for d in RUBRIC:
        means = [per_q[qid]["dims"][d]["mean"] for qid in qids]
        m, _ = _mean_std(means)
        dim_aggregate[d] = round(m, 3)
    weighted_avg_overall = round(
        sum(dim_aggregate[d] * c["weight"] for d, c in RUBRIC.items()), 3
    )

    # Build tokens.json from on-disk artifacts (input/output split, char-length
    # estimates). Aggregator output may be absent at this point — the report is
    # written by Phase 5. Re-run --update-tokens after Phase 5 to populate it.
    tokens_summary = _build_tokens_summary(run_dir, qids, eval_files, label, lang)
    tokens_path = run_dir / "tokens.json"
    _ensure_under_tests(tokens_path)
    tokens_path.write_text(json.dumps(tokens_summary, indent=2, ensure_ascii=False))

    cost_summary = {
        "method": tokens_summary["method"],
        "answers": tokens_summary["answers_total"],
        "evaluations": tokens_summary["evaluations_total"],
        "aggregator": tokens_summary["aggregator"],
        "grand_total": tokens_summary["grand_total"],
    }

    stats = {
        "label": label,
        "run": run,
        "lang": lang,
        "rubric_version": RUBRIC_VERSION,
        "n_evaluators": len(evaluators),
        "n_questions": len(qids),
        "disagreement_threshold": disagreement_threshold,
        "weighted_avg": weighted_avg_overall,
        "dim_aggregate": dim_aggregate,
        "per_question": per_q,
        "flagged_questions": flagged_qs,
        "cost": cost_summary,
        "generated_on": datetime.now(timezone.utc).isoformat(),
    }

    stats_path = run_dir / "stats.json"
    _ensure_under_tests(stats_path)
    stats_path.write_text(json.dumps(stats, indent=2, ensure_ascii=False))

    # Persist a flatter "results" file at tests/results/{label}.{lang}.json
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    results_path = RESULTS_DIR / f"{label}.{lang}.json"
    _ensure_under_tests(results_path)
    results = {
        "label": label,
        "lang": lang,
        "run": run,
        "rubric_version": RUBRIC_VERSION,
        "weighted_avg": weighted_avg_overall,
        "dim_aggregate": dim_aggregate,
        "n_evaluators": len(evaluators),
        "n_questions": len(qids),
        "n_flagged": len(flagged_qs),
        "thresholds": {"max_dim_disagreement": disagreement_threshold},
        "stats_path": str(stats_path),
        "generated_on": stats["generated_on"],
    }
    results_path.write_text(json.dumps(results, indent=2, ensure_ascii=False))

    print(f"[OK] Consolidated {len(evaluators)} evaluators × {len(qids)} questions")
    print(f"     stats:   {stats_path}")
    print(f"     results: {results_path}")
    print(f"     Weighted avg: {weighted_avg_overall:.2f} / 10")
    for d, m in dim_aggregate.items():
        print(f"       {d:20s} ({RUBRIC[d]['weight']*100:.0f}%): {m:.2f}")
    if flagged_qs:
        print(f"     ⚠ {len(flagged_qs)} (Q,dim) pair(s) above disagreement threshold {disagreement_threshold}")


# ----------------------------------------------------------------------
# History
# ----------------------------------------------------------------------

def append_history(label, lang, run, weighted_avg, n_evaluators, n_questions, n_flagged):
    line = (
        f"## [{date.today().isoformat()}] {label} / {lang} / run {run} "
        f"— weighted_avg {weighted_avg:.2f} | {n_evaluators} evaluators × {n_questions} questions | "
        f"{n_flagged} flagged"
    )
    if not HISTORY_FILE.exists():
        HISTORY_FILE.write_text(
            "# Test history\n\nChronological log of /test-vault runs.\n\n"
        )
    with HISTORY_FILE.open("a") as f:
        f.write(line + "\n\n")


# ----------------------------------------------------------------------
# Optional: --compare and --check-repetition (lang-aware, kept from v1)
# ----------------------------------------------------------------------

def _delta_pct(before, after):
    if before == 0:
        return 0.0
    return ((after - before) / before) * 100


def compare_results(from_label, to_label, lang):
    from_file = RESULTS_DIR / f"{from_label}.{lang}.json"
    to_file = RESULTS_DIR / f"{to_label}.{lang}.json"
    if not from_file.exists() or not to_file.exists():
        print(f"[ERR] Missing results for {from_label} or {to_label} (lang={lang})")
        sys.exit(1)
    before = json.loads(from_file.read_text())
    after = json.loads(to_file.read_text())

    rows = []
    for d in RUBRIC:
        b = before["dim_aggregate"][d]
        a = after["dim_aggregate"][d]
        rows.append({
            "dim": d,
            "before": b,
            "after": a,
            "delta_abs": round(a - b, 3),
            "delta_pct": round(_delta_pct(b, a), 2),
        })
    wb = before["weighted_avg"]
    wa = after["weighted_avg"]

    comparison = {
        "from": from_label,
        "to": to_label,
        "lang": lang,
        "rubric_version": RUBRIC_VERSION,
        "weighted_avg": {"before": wb, "after": wa, "delta_abs": round(wa - wb, 3)},
        "dims": rows,
        "generated_on": datetime.now(timezone.utc).isoformat(),
    }

    COMPARISONS_DIR.mkdir(parents=True, exist_ok=True)
    out = COMPARISONS_DIR / f"{to_label}-vs-{from_label}.{lang}.json"
    _ensure_under_tests(out)
    out.write_text(json.dumps(comparison, indent=2, ensure_ascii=False))

    print(f"[Compare {from_label} → {to_label} / {lang}]")
    print(f"  weighted_avg: {wb:.2f} → {wa:.2f}  (Δ {wa-wb:+.3f})")
    for row in rows:
        print(f"    {row['dim']:20s}: {row['before']:.2f} → {row['after']:.2f}  "
              f"(Δ {row['delta_abs']:+.2f}, {row['delta_pct']:+.2f}%)")
    print(f"  Saved: {out}")


def check_repetition(from_label, to_label, lang):
    comp_file = COMPARISONS_DIR / f"{to_label}-vs-{from_label}.{lang}.json"
    if not comp_file.exists():
        print(f"[ERR] No comparison file at {comp_file}; run --compare first")
        sys.exit(2)
    comp = json.loads(comp_file.read_text())
    delta = comp["weighted_avg"]["delta_abs"]
    if abs(delta) < REP_COMPOSITE_NOISE * 10:  # 0.15 on the 0-10 scale
        print(f"REPEAT: weighted_avg delta {delta:+.3f} within noise band")
        sys.exit(1)
    print(f"NO_REPEAT: delta {delta:+.3f} is decisive")
    sys.exit(0)


# ----------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Test Suite Orchestrator (vault-quality framework v2)"
    )
    parser.add_argument("--vault", default=None,
                        help="Vault name (default: active_vault from .claude/state/wikiforge.yaml)")
    parser.add_argument("--lang", default=None,
                        help="Lang code (e.g. en, es)")

    # Subcommands
    parser.add_argument("--generate-questions", action="store_true", dest="generate_questions")
    parser.add_argument("--prepare", action="store_true")
    parser.add_argument("--prepare-evaluator", action="store_true", dest="prepare_evaluator")
    parser.add_argument("--prepare-aggregator", action="store_true", dest="prepare_aggregator")
    parser.add_argument("--consolidate", action="store_true")
    parser.add_argument("--update-tokens", action="store_true", dest="update_tokens",
                        help="Rebuild tokens.json from on-disk artifacts (run after Phase 5 to capture aggregator output)")
    parser.add_argument("--compare", action="store_true")
    parser.add_argument("--check-repetition", action="store_true", dest="check_repetition")
    parser.add_argument("--append-history", action="store_true", dest="append_history",
                        help="Append run summary line to history.md (after consolidate)")

    parser.add_argument("--label", default=None)
    parser.add_argument("--run", type=int, default=None)
    parser.add_argument("--from", dest="from_label", default=None)
    parser.add_argument("--to", dest="to_label", default=None)

    parser.add_argument("--count", type=int, default=None,
                        help=f"Question count (default: vault.yml.tests.count or {DEFAULT_COUNT})")
    parser.add_argument("--mix", default=None,
                        help="Regime mix as A:B:C (default: vault.yml.tests.mix or 5:7:3)")
    parser.add_argument("--evaluators", type=int, default=None,
                        help=f"Number of parallel evaluators (default: vault.yml.tests.evaluators or {DEFAULT_EVALUATORS})")
    parser.add_argument("--regenerate", action="store_true",
                        help="Regenerate questions even if questions.{lang}.yaml exists")
    parser.add_argument("--questions-from", dest="questions_from", default=None,
                        help="Reuse questions from another vault or YAML path "
                             "(e.g. --questions-from oma-test-2 or "
                             "--questions-from path/to/questions.es.yaml). "
                             "Copies into target vault and skips the generator. "
                             "Mutually exclusive with --regenerate.")
    parser.add_argument("--read-queries", action="store_true", dest="read_queries",
                        help="Allow agents/evaluators to read queries/ cache (ablation only — default OFF)")

    args = parser.parse_args()

    _init_vault_config(args.vault)

    # Resolve flags with vault.yml.tests fallback
    count = args.count if args.count is not None else int(_tests_default("count", DEFAULT_COUNT))
    mix = _parse_mix(args.mix or _tests_default("mix", DEFAULT_MIX))
    if sum(mix.values()) != count:
        print(f"[ERR] mix sum ({sum(mix.values())}) != count ({count})")
        sys.exit(1)
    read_queries = args.read_queries or bool(_tests_default("read_queries", False))

    if args.generate_questions:
        if not args.label or not args.lang:
            print("[ERR] --label and --lang required")
            sys.exit(1)
        generate_questions_prompt(args.label, args.lang, count, mix, args.regenerate,
                                  questions_from=args.questions_from)
    elif args.prepare:
        if not args.label or not args.lang:
            print("[ERR] --label and --lang required")
            sys.exit(1)
        prepare_prompts(args.label, args.lang, args.run, read_queries)
    elif args.prepare_evaluator:
        if not args.label or not args.lang:
            print("[ERR] --label and --lang required")
            sys.exit(1)
        prepare_evaluator(args.label, args.lang, args.run, args.evaluators, read_queries)
    elif args.prepare_aggregator:
        if not args.label or not args.lang:
            print("[ERR] --label and --lang required")
            sys.exit(1)
        prepare_aggregator(args.label, args.lang, args.run)
    elif args.consolidate:
        if not args.label or not args.lang:
            print("[ERR] --label and --lang required")
            sys.exit(1)
        consolidate_results(args.label, args.lang, args.run)
        if args.append_history:
            results = json.loads((RESULTS_DIR / f"{args.label}.{args.lang}.json").read_text())
            append_history(
                args.label, args.lang, results["run"], results["weighted_avg"],
                results["n_evaluators"], results["n_questions"], results["n_flagged"],
            )
    elif args.update_tokens:
        if not args.label or not args.lang:
            print("[ERR] --label and --lang required")
            sys.exit(1)
        update_tokens(args.label, args.lang, args.run)
    elif args.compare:
        if not args.from_label or not args.to_label or not args.lang:
            print("[ERR] --from, --to, --lang required")
            sys.exit(1)
        compare_results(args.from_label, args.to_label, args.lang)
    elif args.check_repetition:
        if not args.from_label or not args.to_label or not args.lang:
            print("[ERR] --from, --to, --lang required")
            sys.exit(1)
        check_repetition(args.from_label, args.to_label, args.lang)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
